### ISSUE TITLE
Does this allow extra fields like in e.g. minimap2 output?

### ISSUE THREAD

**Issue by sebschmi** [darcyabjones/paf#1]
Hi,

a minimap2 output PAF line looks for example like this:
```
ctg1    3423273 0       35825   -       NC_000913.3     3421989 0       35833   35825   35833   60      NM:i:8  ms:i:35610      AS:i:35606      nn:i:0  tp:A:P  cm:i:3614       s1:i:35746      s2:i:982        de:f:0.0001     rl:i:0  cg:Z:35109M1D85M2D211M2D77M1D139M2D204M cs:Z::35109-g:85-ta:211-ta:77-c:139-cg:204
```

Does your parser keep all those extra fields?

**Comment by darcyabjones** [comment]
Hi!

I assume you mean everything from `NM:i:8` Yes, it should keeps them as a `Vec<String>`.
The structure is defined here: https://github.com/darcyabjones/paf/blob/681e937ea4d4dad3fc1affc5dd92f6eecce90ba4/src/paf.rs#L135-L144

I mostly wrote this to learn `nom` (based on Heng Li's PAF spec file) so I'm not sure how well it will work with everyone's PAF files but should be fine for minimap2.
I remember thinking about creating some special structures for them (based on what was supposed to be standard) but then realised it would get too strict and less versatile.

It's not super well featured (e.g. there isn't a whole file parser, just a per-line one), but should at least give nice error messages if something is wrong.

Hope that clears it up.

**Comment by sebschmi** [comment]
Thank you so much for the quick answer. I have now actually just written my own (hacky) PAF parser, specific to all the minimap fields, since I need those. Good to know that there is a higher quality version out there though!

If one ever would want to make a good PAF parser with minimap2 support, I think then it should be based off of your parser though. By making the return types more generic, one could implement it for both general PAF, as well as minimap2 PAF.

**Comment by darcyabjones** [comment]
:) I think you're being very generous calling it "high quality", but thankyou.

You're more than welcome to use whatever you want from it if you like, but I'm sure your "hacky" version will be better.

RE return types.
Yeah I think probably a generic type for the optional fields (like here: https://github.com/chfi/rs-gfa/blob/master/src/gafpaf.rs#L175-L186) would be the best option. Then you could have a vector of whatever you want (e.g. an Enum struct or string).
But a fixed struct (e.g. https://docs.rs/rustybam/latest/rustybam/paf/struct.PafRecord.html) is definitely too limiting.

Anyway, good luck with whatever you're working on.
All the best!
